version: 2
 jobs:
   test_classification_model:
     working_directory: ~/project
     docker:
       - image: circleci/python:3.7.2
     steps:
       - checkout
       - run:
           name: Runnning tests
           command: |
             virtualenv venv
             . venv/bin/activate
             pip install --upgrade pip
             pip install -r packages/wafer_fault_detection/requirements.txt
             py.test -vv packages/wafer_fault_detection/tests

 workflows:
   version: 2
   test-all:
     jobs:
       - test_classification_model